# Generated by Django 5.2 on 2025-04-14 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255, verbose_name='Grad')),
                ('street', models.CharField(max_length=255, verbose_name='Ulica')),
                ('street_num', models.IntegerField(verbose_name='Broj ulice')),
                ('constructed_in', models.IntegerField(verbose_name='Izgrađen')),
                ('num_of_floors', models.IntegerField(verbose_name='Spratnost')),
                ('parking', models.BooleanField(verbose_name='Parking')),
                ('garage', models.BooleanField(verbose_name='Graža')),
                ('elevator', models.BooleanField(verbose_name='Lift')),
                ('cctv', models.BooleanField(verbose_name='Video nadzor')),
                ('intercom', models.BooleanField(verbose_name='Interfon')),
            ],
            options={
                'verbose_name': 'Zgrada',
                'verbose_name_plural': 'Zgrade',
                'db_table': 'building',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv')),
            ],
            options={
                'verbose_name': 'Stvar',
                'verbose_name_plural': 'Stvari',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.DateField(verbose_name='Useljiv')),
                ('deposit', models.BooleanField(verbose_name='Depozit')),
                ('for_students', models.BooleanField(verbose_name='Za studente')),
                ('for_workers', models.BooleanField(verbose_name='Za radnike')),
                ('smoking_allowed', models.BooleanField(verbose_name='Dozvoljeno pušenje')),
                ('pets_allowed', models.BooleanField(verbose_name='Dozvoljeni ljubimci')),
            ],
            options={
                'verbose_name': 'Uslovi zakupa',
                'verbose_name_plural': 'Uslovi zakupa',
                'db_table': 'terms',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Lokacija')),
                ('floor', models.IntegerField(verbose_name='Sprat')),
                ('area', models.IntegerField(verbose_name='Površina')),
                ('price', models.IntegerField(verbose_name='Cena')),
                ('num_of_rooms', models.IntegerField(verbose_name='Broj soba')),
                ('state', models.CharField(max_length=255, verbose_name='Stanje')),
                ('heating', models.CharField(max_length=255, verbose_name='Grejanje')),
                ('equipment', models.CharField(max_length=255, verbose_name='Opremljenost')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.building', verbose_name='Zgrada')),
                ('items', models.ManyToManyField(to='listings.item', verbose_name='Stvari')),
            ],
            options={
                'db_table': 'apartment',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Naslov')),
                ('description', models.TextField(verbose_name='Opis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Postavljen')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ažuriran')),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.apartment', verbose_name='Stan')),
                ('terms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.terms', verbose_name='Uslovi zakupa')),
            ],
            options={
                'verbose_name': 'Oglas',
                'verbose_name_plural': 'Oglasi',
                'db_table': 'listing',
            },
        ),
    ]
